### ISSUE TITLE
nwg-dock-hyprland literally dies the moment dolphin gets started

### ISSUE THREAD

**Issue by Andy3153** [nwg-piotr/nwg-dock-hyprland#24]
**Describe the bug**
As the title says, the moment I open Dolphin/if I start the dock with Dolphin already started, the dock segfaults

**To Reproduce**
1. Start dock
2. Start Dolphin
3. Dock dies

OR

1. Start Dolphin
2. Start dock
3. Dock dies the second it starts

**Expected behavior**
Dock doesn't die the moment it touches Dolphin, it shows it on the dock and everything goes as expected

**Desktop (please complete the following information):**
 - Linux distribution: Arch Linux
 - go version: go version go1.21.0 linux/amd64
 - gtk-layer-shell version: 0.8.1-1

**Additional context**
My suspicion is that it really hates the icon Dolphin has and it fails to create a button? It's the default Dolphin icon because I have no idea how to make nwg-dock use a custom icon pack, but that's another issue. Here's what the dock spits out in stdout:
- when the dock is already started and Dolphin gets started after some time:
```
INFO[0000] Starting in autohiDe mode
INFO[0000] Using style: /home/andy3153h/.config/nwg-dock-hyprland/style.css
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5cee77]

goroutine 1 [running]:
github.com/gotk3/gotk3/gtk.(*Image).toWidget(0xc000422aad?)
	<autogenerated>:1 +0x17
main.taskButton.(*Button).SetImage.func4(0xc000334ae0?, {0x7102c0, 0x0})
	/home/piotr/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/gtk/gtk.go:1853 +0x3a
github.com/gotk3/gotk3/gtk.(*Button).SetImage(...)
	/home/piotr/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/gtk/gtk.go:1853
main.taskButton({{0xc000334a90, 0xe}, 0x1, 0x0, {0xc000334ab0, 0x2, 0x2}, {0xc000334ad0, 0x2, 0x2}, ...}, ...)
	/home/piotr/GolandProjects/nwg-dock-hyprland/tools.go:119 +0x18b
main.buildMainBox(0x1?)
	/home/piotr/GolandProjects/nwg-dock-hyprland/main.go:163 +0xa38
main.main.func5.1()
	/home/piotr/GolandProjects/nwg-dock-hyprland/main.go:546 +0x17
reflect.Value.call({0x625f20?, 0xc000327490?, 0xc000257948?}, {0x6d3063, 0x4}, {0x0, 0x0, 0xc0000061a0?})
	/usr/lib/go/src/reflect/value.go:596 +0xce7
reflect.Value.Call({0x625f20?, 0xc000327490?, 0xc0002579e0?}, {0x0?, 0x4c3dfc?, 0x3d?})
	/usr/lib/go/src/reflect/value.go:380 +0xb9
github.com/gotk3/gotk3/glib.sourceFunc(0xc0000061a0?)
	/home/piotr/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/glib/glib.go:324 +0xa5
github.com/gotk3/gotk3/gtk._Cfunc_gtk_main()
	_cgo_gotypes.go:17491 +0x3f
github.com/gotk3/gotk3/gtk.Main(...)
	/home/piotr/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/gtk/gtk.go:1242
main.main()
	/home/piotr/GolandProjects/nwg-dock-hyprland/main.go:647 +0x14ab
```

- when the dock gets started while Dolphin is already started (somehow it's different)
```
INFO[0000] Starting in autohiDe mode
INFO[0000] Using style: /home/andy3153h/.config/nwg-dock-hyprland/style.css
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5cee77]

goroutine 1 [running]:
github.com/gotk3/gotk3/gtk.(*Image).toWidget(0xc0002deaad?)
	<autogenerated>:1 +0x17
main.taskButton.(*Button).SetImage.func4(0xc000014ec0?, {0x7102c0, 0x0})
	/home/piotr/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/gtk/gtk.go:1853 +0x3a
github.com/gotk3/gotk3/gtk.(*Button).SetImage(...)
	/home/piotr/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/gtk/gtk.go:1853
main.taskButton({{0xc000014e70, 0xe}, 0x1, 0x0, {0xc000014e90, 0x2, 0x2}, {0xc000014eb0, 0x2, 0x2}, ...}, ...)
	/home/piotr/GolandProjects/nwg-dock-hyprland/tools.go:119 +0x18b
main.buildMainBox(0x849900?)
	/home/piotr/GolandProjects/nwg-dock-hyprland/main.go:163 +0xa38
main.main()
	/home/piotr/GolandProjects/nwg-dock-hyprland/main.go:557 +0x121e
```

**Comment by nwg-piotr** [comment]
I'll take a look at this when I'm home, but FYI it doesn't happen on my side.

![image](https://github.com/nwg-piotr/nwg-dock-hyprland/assets/20579136/7b2469d8-4b5a-4bba-a2ea-472986a83173)

**Comment by Andy3153** [comment]
Oh wow, didn't expect you to answer so quickly. 

Did you try unsetting the icon theme? Maybe the icon Dolphin ships with is causing problems

**Comment by nwg-piotr** [comment]
Yes. It starts to crash when I set Adwaita instead of Papirus. I'm lookin for possible reason now.

BTW: installing a QT file manager, together with its 46 dependencies, in my all-GTK environment makes little sense.

**Comment by nwg-piotr** [comment]
> Did you try unsetting the icon theme? Maybe the icon Dolphin ships with is causing problems

That's true. Fix on the way. BTW: you will need an icon theme that provides an icon for Dolphin, as `org.kde.dolphin.desktop` does not specify any. Or you may edit the desktop file. Or just give up on Dolphin.

**Comment by nwg-piotr** [comment]
Resolved in https://github.com/nwg-piotr/nwg-dock-hyprland/releases/tag/v0.1.6

**Comment by theRealCarneiro** [comment]
That's still happening with me on 0.1.6, more specifically with Whatsapp Nativefier (while using Papirus Dark icon theme), the dock just crashes with the same errors.
